[project]
name = "python-parallel-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "codetiming>=1.4.0",
    "numpy>=2.2.4",
    "pyyaml>=6.0.2",
    "threadpoolctl>=3.6.0",
]
