[project]
name = "async-getting-started"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.14",
    "codetiming>=1.4.0",
    "requests>=2.32.3",
]
