[project]
name = "rest-apis-with-fast-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "httpie>=3.2.4",
    "mongita>=1.2.0",
]
