import threading

reentrant_lock = threading.RLock()
print('Acquiring a re-entrant lock')
reentrant_lock.acquire()
print('Re-entrant lock acquired')
print('Acquiring a re-entrant lock twice produces **no** deadlock')
reentrant_lock.acquire()
print(reentrant_lock)
print(threading.current_thread())
reentrant_lock.release()
print('Re-entrant lock released')
print(reentrant_lock)
reentrant_lock.release()
print(threading.current_thread())
print('Re-entrant lock released')
